### ISSUE TITLE
ImportError: cannot import name imread

### ISSUE THREAD

**Issue by wlxyhy** [titu1994/Neural-Style-Transfer#17]
Traceback (most recent call last):
  File "Network.py", line 2, in <module>
    from scipy.misc import imread, imresize, imsave, fromimage, toimage
ImportError: cannot import name imread

version:scipy-0.18.1
system:Ubuntu 14.04
PIL was installed,but still it didn't work.

I tried to change "from scipy.misc import imread, imresize, imsave, fromimage, toimage " to "from scipy.misc import * "
then there were other problems:
Traceback (most recent call last):
  File "Network.py", line 10, in <module>
    from keras.models import Sequential
  File "/home/chaoxin/miniconda2/envs/tensorflow/lib/python2.7/site-packages/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/home/chaoxin/miniconda2/envs/tensorflow/lib/python2.7/site-packages/keras/backend/__init__.py", line 69, in <module>
    from .tensorflow_backend import *
  File "/home/chaoxin/miniconda2/envs/tensorflow/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
  File "/home/chaoxin/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/chaoxin/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 45, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/chaoxin/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/chaoxin/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory

**Comment by titu1994** [comment]
Can you try installing pillow instead of pil ? I see you are on Linux so it shouldn't make a difference though. 

As to the second error, I have no clue as to why it occurs. I don't have Tensorflow on Windows so I am unable to test it. But it seems like it cannot access cuda libraries for some reason.

**Comment by titu1994** [comment]
Closing due to no response.

**Comment by wlxyhy** [comment]
Sorry for my late reply, I try to use pillow, but that can't solve it

**Comment by titu1994** [comment]
Can you specify what the error is? 

The `ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory` is not an error in the script, it is an error in loading libcuda. I don't have much experience with Linux so I won't be able to help there.

**Comment by wlxyhy** [comment]
I'm not sure, so I reinstalled the project, there is similar problem :
OSError: libcudart.so.7.5: cannot open shared object file: No such file or directory:
by doing "sudo ldconfig /usr/local/cuda/lib64", I can solve it,but there are other problems,see new issue for detail
