### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by SebastianGS** [titu1994/Neural-Style-Transfer#20]
I followed the installation guide on Windows (I'm using Win7 x64). Tried using both the script helper and the console command but I get the following error:

> Using Theano backend.
Using gpu device 0: GeForce GTX 760 (CNMeM is enabled with initial size: 80.0% of memory, cuDNN None)
Traceback (most recent call last):
  File "inetwork.py", line 8, in <module>
    from keras.models import Sequential
  File "C:\Anaconda3\lib\site-packages\keras\__init__.py", line 2, in <module>
    from . import backend
  File "C:\Anaconda3\lib\site-packages\keras\backend\__init__.py", line 66, in <module>
    from .theano_backend import *
  File "C:\Anaconda3\lib\site-packages\keras\backend\theano_backend.py", line 1, in <module>
    import theano
  File "C:\Anaconda3\lib\site-packages\theano\__init__.py", line 111, in <module>
    theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
  File "C:\Anaconda3\lib\site-packages\theano\sandbox\cuda\tests\test_driver.py", line 31, in test_nvidia_driver1
    profile=False)
  File "C:\Anaconda3\lib\site-packages\theano\compile\function.py", line 320, in function
    output_keys=output_keys)
  File "C:\Anaconda3\lib\site-packages\theano\compile\pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "C:\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 1777, in orig_function
    defaults)
  File "C:\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Anaconda3\lib\site-packages\theano\gof\link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Anaconda3\lib\site-packages\theano\gof\vm.py", line 1003, in make_all
    no_recycling))
  File "C:\Anaconda3\lib\site-packages\theano\sandbox\cuda\__init__.py", line 256, in make_thunk
    compute_map, no_recycling)
  File "C:\Anaconda3\lib\site-packages\theano\gof\op.py", line 970, in make_thunk
    no_recycling)
  File "C:\Anaconda3\lib\site-packages\theano\gof\op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "C:\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "C:\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1595, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1142, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1506, in compile_cmodule
    preargs=preargs)
  File "C:\Anaconda3\lib\site-packages\theano\sandbox\cuda\nvcc_compiler.py", line 362, in compile_str
    nvcc_stdout, nvcc_stderr = decode_iter(p.communicate()[:2])
  File "C:\Anaconda3\lib\site-packages\theano\compat\__init__.py", line 46, in decode_iter
    yield x.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 44: invalid continuation byte

I probably made a stupid mistake somewhere.

Looking forward to your reply. Thank you.

**Comment by titu1994** [comment]
This is a problem with the Theano setup. Please see the docs of Theano to fix it. If that fails, `pip uninstall theano` followed by `pip install --upgrade --no-deps git+https://github.com/Theano/Theano.git` to download and install the master branch of theano.

**Comment by SebastianGS** [comment]
Thanks, it works now!
However, I'm not able to use the script helper (it works fine with console commands.) I get the following error:

`INetwork.py: error: argument --total_variation_weight: invalid float value: '0,00085'`

I tried other values as described in the Guide To Get Good Results, but I keep getting the same error.
