### ISSUE TITLE
Colab Error

### ISSUE THREAD

**Issue by floAr** [titu1994/Neural-Style-Transfer#60]
Error when running the vanilla colab from the page:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "Neural-Style-Transfer/INetwork.py", line 301, in <module>
    base_image = K.variable(preprocess_image(base_image_path, True, read_mode=read_mode))
  File "Neural-Style-Transfer/INetwork.py", line 218, in preprocess_image
    if K.image_dim_ordering() == "th":
AttributeError: module 'keras.backend' has no attribute 'image_dim_ordering'
```

**Comment by titu1994** [comment]
This should be fixed via f7bd07597f6a1042170ad9a1e1f932682a22ef5e

Can you try it out?

**Comment by floAr** [comment]
Nope, you missed it at line 462:

```
Traceback (most recent call last):
  File "Neural-Style-Transfer/INetwork.py", line 521, in <module>
    loss = loss + total_variation_weight * total_variation_loss(combination_image)
  File "Neural-Style-Transfer/INetwork.py", line 462, in total_variation_loss
    if K.image_dim_ordering() == 'th':
AttributeError: module 'keras.backend' has no attribute 'image_dim_ordering'
```

**Comment by titu1994** [comment]
Hmm github edits are difficult. Ok can you try now?

**Comment by floAr** [comment]
Works like a charm. Thanks!

**Comment by titu1994** [comment]
Good to hear.
