### ISSUE TITLE
Replace tf.gradients with tf.GradientTape   :    RuntimeError

### ISSUE THREAD

**Issue by shahmanan5811** [titu1994/Neural-Style-Transfer#69]
Traceback (most recent call last):
  File "Neural-Style-Transfer/INetwork.py", line 524, in <module>
    grads = K.gradients(loss, combination_image)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py", line 3969, in gradients
    loss, variables, colocate_gradients_with_ops=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gradients_impl.py", line 172, in gradients
    unconnected_gradients)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gradients_util.py", line 491, in _GradientsHelper
    raise RuntimeError("tf.gradients is not supported when eager execution "
**_RuntimeError: tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead._**

**Comment by bomtorazek** [comment]
Firstly, import tensorflow as tf

Next, just type the following snippet.

tf.compat.v1.disable_eager_execution()

**Comment by MentalGear** [comment]
You got to add
`%tensorflow_version 1.x`
colab now uses TF 2 by default
